version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - continuerc
  - cursorrules
  - elif
  - frontmatter
  - heredocs
  - lockfiles
  - mktemp
  - PREOF
  - sandboxed
  - whatifwedigdeeper
  - worktrees
ignoreWords: []
import: []
