version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - continuerc
  - cursorrules
  - elif
  - frontmatter
  - whatifwedigdeeper
  - worktrees
ignoreWords: []
import: []
