version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - continuerc
  - cursorrules
  - elif
  - frontmatter
  - GHSA
  - heredocs
  - lockfiles
  - mktemp
  - mypy
  - PREOF
  - pyproject
  - PYSEC
  - pytest
  - REAUDIT
  - sandboxed
  - startswith
  - subshell
  - unupgradable
  - venv
  - vulns
  - whatifwedigdeeper
  - worktrees
ignoreWords: []
import: []
